title: Go SeaHawks!
author: Albert Geacz
theme: minima
email: z1905163@students.niu.edu
description: > # this means to ignore newlines until "baseurl:"
  We like everything Seattle, Russell Wilson will win the MVP this year and the Super Bowl. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
